### ISSUE TITLE
Sometimes adl doesnt pull the correct show number if it has been watched from another computer

### ISSUE THREAD

**Issue by Baitinq** [RaitaroH/adl#17]
Sometimes adl doesnt pull the correct show number if it has been watched from another computer, and only shows the ep number that was left off on the local computer

trackma -a 1 retrieve should fix that problem

Thanks.

**Comment by RaitaroH** [comment]
Soo.... isn't this fixed already? Double so with PR https://github.com/RaitaroH/adl/pull/16 ?
I still want you to take a look at that and see if it works nicely for you @Baitinq

**Comment by RaitaroH** [comment]
Also the title is misleading. adl is using trackma for updating so obv if when trackma get's the list it must be updated unless you did not do that, or as you said, the anime was on another account.

**Comment by RaitaroH** [comment]
> I hadnt seen that, thats very useful. Altough im not sure if it would fix the correct epiisode number not being retrieved as the script doesnt run trackma retrieve at any point.

Hmm `retrieve <> Retrieves the remote list overwrites the local one.` should I just add this to the code then? Except is really slow and can't really be used every time with `trackma list`. So perhaps idk when the script quits instead? Hmm, I would personally go for another `-u` option that would run retrieve instead. Thoughts?
Edit: I want to keep this retrieve discussion here.

**Comment by RaitaroH** [comment]
@Baitinq I thought about this and:
- having an extra adl options is pointless because the user can just run trackma retrieve from time to time;
- trackma retrieve is way too slow to run it at every trackma list instance << implementable but by default set as OFF. That is you could say `$adl -u` or something to also retrieve every time.
- running retrieve at the end of the script would work for the next time I suppose but it still takes time to end the script. << implementable though

Considering the above and that you seem to have issues because you have multiple accounts and computers (am I wrong about that?) I suggest to simply run by yourself trackma retrieve from time to time even as a cronjob OR I will implement an option that will additionaly run 'trackma retrieve'.

If you have a better idea tell me here. For the time being though I consider this to not really be something I can "fix" so to speak because is more of a trackma issue.

**Comment by RaitaroH** [comment]
Example:
```
$ adl -u 
>>> changes $retrieve to 1
```
```bash
retrieve = 0
get_list() { 
   [[ "$retrieve" == "1" ]] && trackma -a "$account" retrieve
   tlist=$(LINES=25 COLUMNS=130 trackma -a "$account" list | head -n -2 | tail -n +2)
}
```

**Comment by Baitinq** [comment]
Thanks for the detailed response. I agree with what you say, and perhaps the best way of doing this would be to add a -u flag like you just stated.

**Comment by RaitaroH** [comment]
@Baitinq check out the new commit. ~If there is nothing to add I will bump the version.~

**Comment by RaitaroH** [comment]
Oh yeah and if trackma receives a non-existent account number, say 10, trackma will prompt the user. No need for adl to do anything here.

**Comment by Baitinq** [comment]
Thanks a lot for your work
