### ISSUE TITLE
Installing on Windows?

### ISSUE THREAD

**Issue by RowanSkie** [RaitaroH/adl#27]

**Comment by RaitaroH** [comment]
Pretty much impossible unless you use the windows subsystem for linux. I will have to port this to python to work, sorry.

**Comment by ArjixWasTaken** [comment]
It's also possible to port to PS (PowerShell). But I have no experience scripting with it.

**Comment by Justaus3r** [comment]
@RaitaroH  it might be possible,following are some workarounds
- Git Bash -install a version of bash that comes with git 
- cygwin - a POSIX compatible shell capable to run linux native programs
- Linux subsystem for windows that u mentioned

i actually tried it with Git Bash ,it can theoretically work if you can do something about trackma then it will be good to go. or just install cygwin and check on it ,it has far better chance and yeah using WSL will ensure that it's working ,just that it has a large size(i mean installing a linux distro)

**Comment by RaitaroH** [comment]
@Justaus3r I think Git bash is enough. I managed to get adl working. There are some issues like checking for dependencies inside the script will not work. So [this line](https://github.com/RaitaroH/adl/blob/a1fa123c1e4ba972b0ec1205e75e6e02de942ca0/adl#L606) needs to be commented out. Also ueberzug did not install using pip on windows.

First you will need [Git for Windows](https://gitforwindows.org/) to be able to run bash scripts. 
```
choco install -y git.install
```

Then dependencies for "anime-downloader" and "adl"
```
choco install -y python3 aria2 mpv fzf
# restart shell
```

Install python dependencies:
```
pip install -U git+https://github.com/anime-dl/anime-downloader Trackma
```

Setup trackma by running "trackma" and following the prompts. You will have to get the token from Anilist.

Comment out [this line](https://github.com/RaitaroH/adl/blob/a1fa123c1e4ba972b0ec1205e75e6e02de942ca0/adl#L606).
Now you can finally run adl.
In CMD you can use "bash.exe" to run adl. In this case adl.sh in the current directory:
```
"C:\Program Files\Git\bin\bash.exe" ".\adl.sh"
```
In PowerShell run this:
```
cmd /c "C:\Program Files\Git\bin\bash.exe" ".\adl.sh"
```
You may want to change the terminal colors for better readability :)

**Comment by Justaus3r** [comment]
@RaitaroH  OK so i tinkered a bit with the script and modified ```check_player``` function so that it would work on windows.
the logic i am using is that i have specified a variable containing a windows specific command(i.e ```ipconfig```) and  we check that command every time adl runs,this command will off-course fail on linux(unless someone has made a symlink or alias of that command,whichi is pretty rare).on windows this command will succeed because ```System32``` is on PATH of git-bash.by using that if the platform is windows then a a simple batch file is invoked ,if the player is on PATH,then ```1``` is written to a file other wise ```0``` is written to the file.our bash script then reads that file and depending on the value ,our script shows an error or continues.i also changed the default provider to "animerush"  as it provides **much** better search results than the default provider,tho a little dependency(nodejs) is added(which is already needed for some providers).i will PR the changes ,you can merge them if you are satisfied with the changes.

**Comment by Justaus3r** [comment]
>> Also ueberzug did not install using pip on windows.

Yeah about that,you need Microsoft's build tools for visual studio,which is a lot of hassle btw.
