### ISSUE TITLE
Adl chooses top option for anime-downloader automatically

### ISSUE THREAD

**Issue by cronyakatsuki** [RaitaroH/adl#28]
In the last couple of days I have had the problem of adl automatically choosing the top option of anime-downloader search. That is done without the adl-y flag so I dont know why does it happen. I installed adl form the github and anime-downloader from the pip. (I used arch aur packages before but had the same problem so I tried official installation methods.). Adl -y does work,.

**Comment by RaitaroH** [comment]
Please read this in the `Requirements`. 
> Settings for anime-downloader, such as provider, need to be placed in your configuration file, as instructed in the documentation.
I didn't give adl the option of provider choosing because I thought it was a bit too much. I am not saying it can't be implemented, but just I don't think is necessary. Not to mention, anime downloader is very picky and most websites don't even work for the most part.

If I clarified your issue please close this. Oh and I wll add a watch from local storage option like tomorrow.

**Comment by RaitaroH** [comment]
Or you are not referring to providers?

**Comment by RaitaroH** [comment]
@CroLinuxGamer yeah actually nevermind, I found what you mean. anime-downloader changed the behaviour of `-c` option so now `-c 0` will auto-choose, instead of not doing anything.

**Comment by RaitaroH** [comment]
Pffff, anyhow, I fixed this.

**Comment by RaitaroH** [comment]
Fixed in develop branch. I will merge into master soon-ish. You can use the `adl -u` to update to develop if you want or do it manually. (I put stuff in develop so that I can test a bit more before it ends up in master)

**Comment by cronyakatsuki** [comment]
Thank you very much on quickly adding the fix and sorry for answering so late I wasn't close to my pc.
